// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BTCBATTLE_PROTO_BATTLE_PACKET_H_
#define FLATBUFFERS_GENERATED_BTCBATTLE_PROTO_BATTLE_PACKET_H_

#include "flatbuffers/flatbuffers.h"

namespace proto_battle {
namespace packet {

struct LOGIN_Req;

struct LOGIN_Ack;

struct LOGOUT_Req;

struct LOGOUT_Ack;

struct DATA_Req;

struct DATA_Ack;

}  // namespace packet

enum class PROTOCOL : uint16_t {
  PING = 0,
  PONG = 1,
  LOGIN = 4097,
  LOGOUT = 4105,
  DATA = 36865,
  BASE = 65535,
  MIN = PING,
  MAX = BASE
};

inline const PROTOCOL (&EnumValuesPROTOCOL())[6] {
  static const PROTOCOL values[] = {
    PROTOCOL::PING,
    PROTOCOL::PONG,
    PROTOCOL::LOGIN,
    PROTOCOL::LOGOUT,
    PROTOCOL::DATA,
    PROTOCOL::BASE
  };
  return values;
}

inline const char *EnumNamePROTOCOL(PROTOCOL e) {
  switch (e) {
    case PROTOCOL::PING: return "PING";
    case PROTOCOL::PONG: return "PONG";
    case PROTOCOL::LOGIN: return "LOGIN";
    case PROTOCOL::LOGOUT: return "LOGOUT";
    case PROTOCOL::DATA: return "DATA";
    case PROTOCOL::BASE: return "BASE";
    default: return "";
  }
}

enum class RESULT : uint16_t {
  SUCCESS = 0,
  FAILURE = 1,
  BASE = 65535,
  MIN = SUCCESS,
  MAX = BASE
};

inline const RESULT (&EnumValuesRESULT())[3] {
  static const RESULT values[] = {
    RESULT::SUCCESS,
    RESULT::FAILURE,
    RESULT::BASE
  };
  return values;
}

inline const char *EnumNameRESULT(RESULT e) {
  switch (e) {
    case RESULT::SUCCESS: return "SUCCESS";
    case RESULT::FAILURE: return "FAILURE";
    case RESULT::BASE: return "BASE";
    default: return "";
  }
}

namespace packet {

struct LOGIN_Req FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USER_TOKEN = 4
  };
  const flatbuffers::String *user_token() const {
    return GetPointer<const flatbuffers::String *>(VT_USER_TOKEN);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_USER_TOKEN) &&
           verifier.VerifyString(user_token()) &&
           verifier.EndTable();
  }
};

struct LOGIN_ReqBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_user_token(flatbuffers::Offset<flatbuffers::String> user_token) {
    fbb_.AddOffset(LOGIN_Req::VT_USER_TOKEN, user_token);
  }
  explicit LOGIN_ReqBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LOGIN_ReqBuilder &operator=(const LOGIN_ReqBuilder &);
  flatbuffers::Offset<LOGIN_Req> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LOGIN_Req>(end);
    return o;
  }
};

inline flatbuffers::Offset<LOGIN_Req> CreateLOGIN_Req(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> user_token = 0) {
  LOGIN_ReqBuilder builder_(_fbb);
  builder_.add_user_token(user_token);
  return builder_.Finish();
}

inline flatbuffers::Offset<LOGIN_Req> CreateLOGIN_ReqDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *user_token = nullptr) {
  auto user_token__ = user_token ? _fbb.CreateString(user_token) : 0;
  return proto_battle::packet::CreateLOGIN_Req(
      _fbb,
      user_token__);
}

struct LOGIN_Ack FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USER_NICK = 4
  };
  const flatbuffers::String *user_nick() const {
    return GetPointer<const flatbuffers::String *>(VT_USER_NICK);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_USER_NICK) &&
           verifier.VerifyString(user_nick()) &&
           verifier.EndTable();
  }
};

struct LOGIN_AckBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_user_nick(flatbuffers::Offset<flatbuffers::String> user_nick) {
    fbb_.AddOffset(LOGIN_Ack::VT_USER_NICK, user_nick);
  }
  explicit LOGIN_AckBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LOGIN_AckBuilder &operator=(const LOGIN_AckBuilder &);
  flatbuffers::Offset<LOGIN_Ack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LOGIN_Ack>(end);
    return o;
  }
};

inline flatbuffers::Offset<LOGIN_Ack> CreateLOGIN_Ack(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> user_nick = 0) {
  LOGIN_AckBuilder builder_(_fbb);
  builder_.add_user_nick(user_nick);
  return builder_.Finish();
}

inline flatbuffers::Offset<LOGIN_Ack> CreateLOGIN_AckDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *user_nick = nullptr) {
  auto user_nick__ = user_nick ? _fbb.CreateString(user_nick) : 0;
  return proto_battle::packet::CreateLOGIN_Ack(
      _fbb,
      user_nick__);
}

struct LOGOUT_Req FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEST1 = 4,
    VT_TEST2 = 6
  };
  uint32_t test1() const {
    return GetField<uint32_t>(VT_TEST1, 0);
  }
  uint32_t test2() const {
    return GetField<uint32_t>(VT_TEST2, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TEST1) &&
           VerifyField<uint32_t>(verifier, VT_TEST2) &&
           verifier.EndTable();
  }
};

struct LOGOUT_ReqBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_test1(uint32_t test1) {
    fbb_.AddElement<uint32_t>(LOGOUT_Req::VT_TEST1, test1, 0);
  }
  void add_test2(uint32_t test2) {
    fbb_.AddElement<uint32_t>(LOGOUT_Req::VT_TEST2, test2, 0);
  }
  explicit LOGOUT_ReqBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LOGOUT_ReqBuilder &operator=(const LOGOUT_ReqBuilder &);
  flatbuffers::Offset<LOGOUT_Req> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LOGOUT_Req>(end);
    return o;
  }
};

inline flatbuffers::Offset<LOGOUT_Req> CreateLOGOUT_Req(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t test1 = 0,
    uint32_t test2 = 0) {
  LOGOUT_ReqBuilder builder_(_fbb);
  builder_.add_test2(test2);
  builder_.add_test1(test1);
  return builder_.Finish();
}

struct LOGOUT_Ack FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEST1 = 4,
    VT_TEST2 = 6,
    VT_TEST3 = 8,
    VT_TEST4 = 10
  };
  uint32_t test1() const {
    return GetField<uint32_t>(VT_TEST1, 0);
  }
  uint32_t test2() const {
    return GetField<uint32_t>(VT_TEST2, 0);
  }
  uint32_t test3() const {
    return GetField<uint32_t>(VT_TEST3, 0);
  }
  uint32_t test4() const {
    return GetField<uint32_t>(VT_TEST4, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TEST1) &&
           VerifyField<uint32_t>(verifier, VT_TEST2) &&
           VerifyField<uint32_t>(verifier, VT_TEST3) &&
           VerifyField<uint32_t>(verifier, VT_TEST4) &&
           verifier.EndTable();
  }
};

struct LOGOUT_AckBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_test1(uint32_t test1) {
    fbb_.AddElement<uint32_t>(LOGOUT_Ack::VT_TEST1, test1, 0);
  }
  void add_test2(uint32_t test2) {
    fbb_.AddElement<uint32_t>(LOGOUT_Ack::VT_TEST2, test2, 0);
  }
  void add_test3(uint32_t test3) {
    fbb_.AddElement<uint32_t>(LOGOUT_Ack::VT_TEST3, test3, 0);
  }
  void add_test4(uint32_t test4) {
    fbb_.AddElement<uint32_t>(LOGOUT_Ack::VT_TEST4, test4, 0);
  }
  explicit LOGOUT_AckBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LOGOUT_AckBuilder &operator=(const LOGOUT_AckBuilder &);
  flatbuffers::Offset<LOGOUT_Ack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LOGOUT_Ack>(end);
    return o;
  }
};

inline flatbuffers::Offset<LOGOUT_Ack> CreateLOGOUT_Ack(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t test1 = 0,
    uint32_t test2 = 0,
    uint32_t test3 = 0,
    uint32_t test4 = 0) {
  LOGOUT_AckBuilder builder_(_fbb);
  builder_.add_test4(test4);
  builder_.add_test3(test3);
  builder_.add_test2(test2);
  builder_.add_test1(test1);
  return builder_.Finish();
}

struct DATA_Req FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UBYTE_LIST = 4
  };
  const flatbuffers::Vector<uint8_t> *ubyte_list() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_UBYTE_LIST);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UBYTE_LIST) &&
           verifier.VerifyVector(ubyte_list()) &&
           verifier.EndTable();
  }
};

struct DATA_ReqBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_ubyte_list(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> ubyte_list) {
    fbb_.AddOffset(DATA_Req::VT_UBYTE_LIST, ubyte_list);
  }
  explicit DATA_ReqBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  DATA_ReqBuilder &operator=(const DATA_ReqBuilder &);
  flatbuffers::Offset<DATA_Req> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<DATA_Req>(end);
    return o;
  }
};

inline flatbuffers::Offset<DATA_Req> CreateDATA_Req(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> ubyte_list = 0) {
  DATA_ReqBuilder builder_(_fbb);
  builder_.add_ubyte_list(ubyte_list);
  return builder_.Finish();
}

inline flatbuffers::Offset<DATA_Req> CreateDATA_ReqDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *ubyte_list = nullptr) {
  auto ubyte_list__ = ubyte_list ? _fbb.CreateVector<uint8_t>(*ubyte_list) : 0;
  return proto_battle::packet::CreateDATA_Req(
      _fbb,
      ubyte_list__);
}

struct DATA_Ack FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROOM_IDX = 4,
    VT_SENDER_UID = 6,
    VT_UBYTE_LIST = 8
  };
  uint16_t room_idx() const {
    return GetField<uint16_t>(VT_ROOM_IDX, 0);
  }
  uint64_t sender_uid() const {
    return GetField<uint64_t>(VT_SENDER_UID, 0);
  }
  const flatbuffers::Vector<uint8_t> *ubyte_list() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_UBYTE_LIST);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_ROOM_IDX) &&
           VerifyField<uint64_t>(verifier, VT_SENDER_UID) &&
           VerifyOffset(verifier, VT_UBYTE_LIST) &&
           verifier.VerifyVector(ubyte_list()) &&
           verifier.EndTable();
  }
};

struct DATA_AckBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_room_idx(uint16_t room_idx) {
    fbb_.AddElement<uint16_t>(DATA_Ack::VT_ROOM_IDX, room_idx, 0);
  }
  void add_sender_uid(uint64_t sender_uid) {
    fbb_.AddElement<uint64_t>(DATA_Ack::VT_SENDER_UID, sender_uid, 0);
  }
  void add_ubyte_list(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> ubyte_list) {
    fbb_.AddOffset(DATA_Ack::VT_UBYTE_LIST, ubyte_list);
  }
  explicit DATA_AckBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  DATA_AckBuilder &operator=(const DATA_AckBuilder &);
  flatbuffers::Offset<DATA_Ack> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<DATA_Ack>(end);
    return o;
  }
};

inline flatbuffers::Offset<DATA_Ack> CreateDATA_Ack(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t room_idx = 0,
    uint64_t sender_uid = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> ubyte_list = 0) {
  DATA_AckBuilder builder_(_fbb);
  builder_.add_sender_uid(sender_uid);
  builder_.add_ubyte_list(ubyte_list);
  builder_.add_room_idx(room_idx);
  return builder_.Finish();
}

inline flatbuffers::Offset<DATA_Ack> CreateDATA_AckDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t room_idx = 0,
    uint64_t sender_uid = 0,
    const std::vector<uint8_t> *ubyte_list = nullptr) {
  auto ubyte_list__ = ubyte_list ? _fbb.CreateVector<uint8_t>(*ubyte_list) : 0;
  return proto_battle::packet::CreateDATA_Ack(
      _fbb,
      room_idx,
      sender_uid,
      ubyte_list__);
}

}  // namespace packet
}  // namespace proto_battle

#endif  // FLATBUFFERS_GENERATED_BTCBATTLE_PROTO_BATTLE_PACKET_H_
